import initTabNav from "./modules/tab-nav.js";
import initAccordion from "./modules/accordion.js";
import initScrollReveal from "./modules/scroll-reveal.js";
import initModal from "./modules/modal.js";
import initTooltip from "./modules/tooltip.js";
import initDropdown from "./modules/dropdown.js";
import initMenuMobile from "./modules/menu-mobile.js";
// import initAnimaNumber from "./modules/anime-number.js";
import initFuncionamento from "./modules/funcionamento.js";
import initAnimaisFetch from "./modules/animais-fetch.js";

initTabNav();
initAccordion();
initScrollReveal();
initModal();
initTooltip();
initDropdown();
initMenuMobile();
// initAnimaNumber();
initFuncionamento();
initAnimaisFetch();